### ISSUE TITLE
Feature request: Add fields for hugo theme and htmlwidgets

### ISSUE THREAD

**Issue by p0bs** [sellorm/awesome-blogdown#2]
Thanks for doing this.

Just a quick idea, along the lines of [my SO question](https://stackoverflow.com/questions/44250048/which-hugo-themes-support-unaided-htmlwidgets-when-using-blogdown): Would it be possible to add fields for the hugo theme being implemented and whether htmlwidgets are working on the site? I only ask, as this would be really helpful to me (and presumably others) in choosing which hugo theme would work best, given the needs in question.

Thanks again.

**Comment by sellorm** [comment]
Hi Robin,

Thanks for the idea. Sadly, I think it would be very tricky to implement. It would require checking all the sites listed for whether they were using an off-the-shelf theme, or a custom theme and then trawling each site to see if they had published anything with htmlwidgets, and then checks to see if that worked properly. This would be error prone and manual to say the least.

Having said that, I can see a genuine need for blogdown specific themes gallery (like the main hugo one here ->  http://themes.gohugo.io), that indicates whether or not each theme supports specific features like htmlwidgets.

That idea doesn't really fit with awesome-blogdown, but would make a great community project to either start yourself (as you sound like you have some experience here! ;) ) or to suggest over on the main blogdown repo -> https://github.com/rstudio/blogdown

Thanks for taking the time to share your suggestion, and if you do decide to take it any further, let me know if I can be of any help!

Cheers,
Mark
