### ISSUE TITLE
website not available - https://jsonbaik.rbind.io

### ISSUE THREAD

**Issue by sellorm** [sellorm/awesome-blogdown#64]
Hi @jasonbaik94,

Your blogdown site appears to be unavailable.

Is this expected on at your end?

Just checking as it's still listed on awesome-blogdown.com but my checker is throwing an error for it.

Cheers,
Mark

**Comment by jasonbaik94** [comment]
Hi Mark, 

Yes that is expected since I closed it down so I can make a new blogdown with another theme

Thanks for checking!
Jason
