### ISSUE TITLE
New site

### ISSUE THREAD

**Issue by AlyshaDeLivera** [sellorm/awesome-blogdown#88]
## New Site

**NAME:** Alysha De Livera

**URL:** https://alyshadelivera.netlify.app/

**Description:** Alysha De Livera's academic website

**Comment by sellorm** [comment]
Hi Alysha, thanks for the raising this issue.

Just to confirm, is your site made with blogdown? It says it was made with wowchemy in the footer.

**Comment by AlyshaDeLivera** [comment]
Hi Mark,

Thanks for this. Yes, definitely with blogdown, using the theme wowchemy/starter-academic.

Best wishes,
Alysha

Dr Alysha De Livera
Senior Lecturer in Statistics
Mathematics and Statistics, School of Computing, Engineering and Mathematical Sciences
La Trobe University | Melbourne (Bundoora) 3086, Australia
T: +61 3 9479 6587 |  W: https://alyshadelivera.netlify.app | Google scholar: https://scholar.google.com/citations?user=zLbHjEIAAAAJ | LinkedIn: https://www.linkedin.com/in/alysha-de-livera/ | Twitter: https://twitter.com/AlyshaDeLivera
***@***.***
CRICOS Provider 00115M
We are proud to acknowledge the Wurundjeri people of the Kulin Nation as the traditional custodians of the land on which La Trobe Bundoora is located.
Please kindly consider your environment before printing this e-mail.
Warning to recipients:
This email and any attachments are confidential and subject to copyright. If you are not the intended recipient any use, disclosure or copying is unauthorised. If you have received this email in error, please advise us immediately by reply email and delete all copies. It is your responsibility to examine this email and any attachments for viruses. Any personal information in this email must be handled in accordance with the Privacy and Data Protection Act 2014 (Vic).

**Comment by sellorm** [comment]
Thanks for the clarification, Alysha, it's much appreciated.

Your site is now live on awesome-blogdown.com :tada:

**Comment by AlyshaDeLivera** [comment]
Thanks Mark.

Best wishes,
Alysha

Dr Alysha De Livera
Senior Lecturer in Statistics
Mathematics and Statistics, School of Computing, Engineering and Mathematical Sciences
La Trobe University | Melbourne (Bundoora) 3086, Australia
T: +61 3 9479 6587 |  W: https://alyshadelivera.netlify.app | Google scholar: https://scholar.google.com/citations?user=zLbHjEIAAAAJ | LinkedIn: https://www.linkedin.com/in/alysha-de-livera/ | Twitter: https://twitter.com/AlyshaDeLivera
***@***.***
CRICOS Provider 00115M
We are proud to acknowledge the Wurundjeri people of the Kulin Nation as the traditional custodians of the land on which La Trobe Bundoora is located.
Please kindly consider your environment before printing this e-mail.
Warning to recipients:
This email and any attachments are confidential and subject to copyright. If you are not the intended recipient any use, disclosure or copying is unauthorised. If you have received this email in error, please advise us immediately by reply email and delete all copies. It is your responsibility to examine this email and any attachments for viruses. Any personal information in this email must be handled in accordance with the Privacy and Data Protection Act 2014 (Vic).
